data_dir: "data/"
image_size: 224
patch_size: 16
in_channels: 3
n_heads: 8
d_token: 64
n_enc_layers: 4
n_dec_layers: 4
batch_size: 8
clip_len: 8
normalize:
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
db_loc: "db.json"
checkpoint_dir: "checkpoints/"
use_checkpoints: True
dataset_time: 480
fetch_urls: False