data_dir: "data/"
image_size: 224
patch_size: 16
in_channels: 3
n_heads: 8
d_token: 64
n_enc_layers: 12
n_dec_layers: 12
batch_size: 1
clip_len: 6
normalize:
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
db_loc: "db.json"
checkpoint_dir: "checkpoints/"
use_checkpoints: False
dataset_time: 480
fetch_urls: False